name: PR Labeler
on: [pull_request_target]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v4.3.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
