name: TypeScript Check
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check TypeScript
        run: |
          git fetch origin main:main
          FILES=$(git diff --name-only main... | grep '\.ts$')
          if [ -n "$FILES" ]; then
            yarn ts-check $FILES
          else
            echo "No TypeScript files have changed"
          fi
